### ISSUE TITLE
Mobi-act dataset not available

### ISSUE THREAD

**Issue by Farah032** [IKKIM00/Fall-Detection-and-Prediction#1]
Hi

I am implementing the paper for study purposes and I read your papers and codes. But the problem is Mobiact data is not available on the given URL (https://bmi.hmu.gr/the-mobifall-and-mobiact-datasets-2/). Is that possible for you can help me with it?
I need raw data for my understanding.

It will help me in the learning process.

**Comment by IKKIM00** [comment]
Hi, Sorry for leaving the comments bit late.
I just checked the URL I have attached, but it seems like you can request the public data through email.
It seems like they changed there policy but data is still available.
